function ConvertTo-PSPipelineScript {
    <#
    .SYNOPSIS
        Compiles a pipeline definition into a single, fully self-contained
        PowerShell script that exposes the pipeline as one function.
    .DESCRIPTION
        The generated .ps1 has zero dependencies on this module: the core
        transform functions are inlined, the pipeline definition is embedded
        as JSON, and the whole thing runs on Windows PowerShell 5.1+ — so it
        can be copied to a locked-down machine and dot-sourced as-is.
    .PARAMETER Path
        Path to a pipeline definition .json file (saved from the visual designer).
    .PARAMETER OutputPath
        Where to write the generated .ps1. If omitted, the script text is returned.
    .PARAMETER FunctionName
        Name of the generated function. Default: Invoke-DataPipeline.
    .EXAMPLE
        ConvertTo-PSPipelineScript -Path .\samples\sample-pipeline.json -OutputPath .\Invoke-DataPipeline.ps1
        .\Invoke-DataPipeline.ps1 -Verbose          # run the pipeline directly
        Get-Help .\Invoke-DataPipeline.ps1 -Full     # the generated script self-documents
    .NOTES
        The generated script carries comment-based help, a -Help switch, and a single
        entry function (default Invoke-DataPipeline). Run it directly to execute the
        pipeline, or dot-source it to load the function. The transform engine is inlined
        in a clearly fenced "Embedded engine" region.
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory, Position = 0)]
        [string]$Path,

        [Parameter(Position = 1)]
        [string]$OutputPath,

        [ValidatePattern('^[A-Za-z][A-Za-z0-9-]*$')]
        [string]$FunctionName = 'Invoke-DataPipeline'
    )

    $json = (Get-Content -Path $Path -Raw).Trim()
    $definition = $json | ConvertFrom-Json   # validates the JSON before embedding it
    if ($json -match "(?m)^'@") {
        throw "The pipeline JSON contains a line beginning with '@', which would terminate the embedded here-string. Re-save the definition with different formatting."
    }

    $corePath = Join-Path -Path (Join-Path -Path $script:ModuleRoot -ChildPath 'Core') -ChildPath 'PipelineFunctions.ps1'
    $coreSource = Get-Content -Path $corePath -Raw

    $pipelineName = if ($definition.name) { [string]$definition.name } else { (Split-Path -Path $Path -Leaf) }
    $params = @($definition.parameters | Where-Object { $_ -and $_.name })

    $lines = New-Object System.Collections.Generic.List[string]
    [void]$lines.Add('#Requires -Version 5.1')
    [void]$lines.Add('')
    [void]$lines.Add('<#')
    [void]$lines.Add('.SYNOPSIS')
    [void]$lines.Add('    Run the "' + $pipelineName + '" data pipeline. Self-contained: no module, no install, PowerShell 5.1+.')
    [void]$lines.Add('.DESCRIPTION')
    [void]$lines.Add('    Generated by PSPipeline. Reads the inputs, applies the transforms, and writes the')
    [void]$lines.Add('    outputs described by the pipeline embedded below. The transform engine is inlined in')
    [void]$lines.Add('    the "Embedded engine" region near the foot of the file; you should not need to read')
    [void]$lines.Add('    or edit it.')
    [void]$lines.Add('')
    [void]$lines.Add('    Run this script directly to execute the pipeline, or dot-source it to load the')
    [void]$lines.Add('    ' + $FunctionName + ' function and call it yourself.')
    [void]$lines.Add('.PARAMETER BasePath')
    [void]$lines.Add('    Directory that relative input/output paths resolve against. Defaults to the working directory.')
    foreach ($p in $params) {
        $pd = if ([string]::IsNullOrEmpty([string]$p.default)) { '(empty)' } else { [string]$p.default }
        [void]$lines.Add('.PARAMETER ' + $p.name)
        [void]$lines.Add('    Pipeline parameter (default: ' + $pd + ').')
    }
    [void]$lines.Add('.PARAMETER Help')
    [void]$lines.Add('    Show this help and exit.')
    [void]$lines.Add('.EXAMPLE')
    [void]$lines.Add('    .\' + $FunctionName + '.ps1')
    [void]$lines.Add('    Run the pipeline against files in the current directory.')
    [void]$lines.Add('.EXAMPLE')
    [void]$lines.Add('    .\' + $FunctionName + '.ps1 -BasePath C:\Data -Verbose')
    [void]$lines.Add('.EXAMPLE')
    [void]$lines.Add('    . .\' + $FunctionName + '.ps1; ' + $FunctionName)
    [void]$lines.Add('    Dot-source to load the function, then call it.')
    [void]$lines.Add('.NOTES')
    [void]$lines.Add('    Pipeline : ' + $pipelineName)
    [void]$lines.Add('    Generated: ' + (Get-Date -Format 'yyyy-MM-dd HH:mm') + ' by PSPipeline')
    [void]$lines.Add('#>')
    [void]$lines.Add('')
    [void]$lines.Add('[CmdletBinding()]')
    [void]$lines.Add('param(')
    [void]$lines.Add('    [string]$BasePath,')
    foreach ($p in $params) {
        $pDefault = ([string]$p.default).Replace("'", "''")
        [void]$lines.Add("    [string]`$$($p.name) = '$pDefault',")
    }
    [void]$lines.Add('    [switch]$Help')
    [void]$lines.Add(')')
    [void]$lines.Add('')
    [void]$lines.Add('function ' + $FunctionName + ' {')
    [void]$lines.Add('    <#')
    [void]$lines.Add('    .SYNOPSIS')
    [void]$lines.Add('        Run the embedded "' + $pipelineName + '" pipeline and return its result rows.')
    [void]$lines.Add('    .PARAMETER BasePath')
    [void]$lines.Add('        Directory that relative input/output paths resolve against.')
    [void]$lines.Add('    #>')
    [void]$lines.Add('    [CmdletBinding()]')
    [void]$lines.Add('    param(')
    if ($params.Count) {
        [void]$lines.Add('        [string]$BasePath,')
        for ($pi = 0; $pi -lt $params.Count; $pi++) {
            $pDefault = ([string]$params[$pi].default).Replace("'", "''")
            $pComma = if ($pi -lt $params.Count - 1) { ',' } else { '' }
            [void]$lines.Add("        [string]`$$($params[$pi].name) = '$pDefault'$pComma")
        }
    }
    else {
        [void]$lines.Add('        [string]$BasePath')
    }
    [void]$lines.Add('    )')
    [void]$lines.Add('')
    [void]$lines.Add("    `$pipelineJson = @'")
    [void]$lines.Add($json)
    [void]$lines.Add("'@")
    [void]$lines.Add('')
    [void]$lines.Add('    $Params = @{}')
    foreach ($p in $params) {
        [void]$lines.Add("    `$Params['$(([string]$p.name).Replace("'","''"))'] = `$$($p.name)")
    }
    [void]$lines.Add('')
    [void]$lines.Add('    if ($BasePath) { Push-Location -Path $BasePath }')
    [void]$lines.Add('    try {')
    [void]$lines.Add('        Invoke-PipelineDefinition -Definition ($pipelineJson | ConvertFrom-Json) -Parameters $Params')
    [void]$lines.Add('    }')
    [void]$lines.Add('    finally {')
    [void]$lines.Add('        if ($BasePath) { Pop-Location }')
    [void]$lines.Add('    }')
    [void]$lines.Add('}')
    [void]$lines.Add('')
    [void]$lines.Add('# ===========================================================================')
    [void]$lines.Add('#   Embedded transform engine')
    [void]$lines.Add('#   Inlined from PSPipeline Core/PipelineFunctions.ps1 -- generated code.')
    [void]$lines.Add('#   Do not edit by hand; regenerate with ConvertTo-PSPipelineScript.')
    [void]$lines.Add('# ===========================================================================')
    [void]$lines.Add('')
    [void]$lines.Add($coreSource.TrimEnd())
    [void]$lines.Add('')
    [void]$lines.Add('# ===========================================================================')
    [void]$lines.Add('#   End embedded engine')
    [void]$lines.Add('# ===========================================================================')
    [void]$lines.Add('')
    [void]$lines.Add('# Entry point: run the pipeline when this file is executed directly; when it is')
    [void]$lines.Add('# dot-sourced (". .\' + $FunctionName + '.ps1") only the function above is defined.')
    [void]$lines.Add('if ($Help) { Get-Help -Name $PSCommandPath -Full; return }')
    [void]$lines.Add("if (`$MyInvocation.InvocationName -ne '.') {")
    [void]$lines.Add("    [void]`$PSBoundParameters.Remove('Help')")
    [void]$lines.Add('    ' + $FunctionName + ' @PSBoundParameters')
    [void]$lines.Add('}')

    $scriptText = $lines -join [Environment]::NewLine

    if ($OutputPath) {
        Set-Content -Path $OutputPath -Value $scriptText -Encoding UTF8
        Get-Item -Path $OutputPath
    }
    else {
        $scriptText
    }
}
