function ConvertTo-PSPipelineScript {
    <#
    .SYNOPSIS
        Compiles a pipeline definition into a single, fully self-contained
        PowerShell script that exposes the pipeline as one function.
    .DESCRIPTION
        The generated .ps1 has zero dependencies on this module: the core
        transform functions are inlined, the pipeline definition is embedded
        as JSON, and the whole thing runs on Windows PowerShell 5.1+ — so it
        can be copied to a locked-down machine and dot-sourced as-is.
    .PARAMETER Path
        Path to a pipeline definition .json file (saved from the visual designer).
    .PARAMETER OutputPath
        Where to write the generated .ps1. If omitted, the script text is returned.
    .PARAMETER FunctionName
        Name of the generated function. Default: Invoke-DataPipeline.
    .EXAMPLE
        ConvertTo-PSPipelineScript -Path .\samples\sample-pipeline.json -OutputPath .\Invoke-DataPipeline.ps1
        . .\Invoke-DataPipeline.ps1
        Invoke-DataPipeline -Verbose
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory, Position = 0)]
        [string]$Path,

        [Parameter(Position = 1)]
        [string]$OutputPath,

        [ValidatePattern('^[A-Za-z][A-Za-z0-9-]*$')]
        [string]$FunctionName = 'Invoke-DataPipeline'
    )

    $json = (Get-Content -Path $Path -Raw).Trim()
    $definition = $json | ConvertFrom-Json   # validates the JSON before embedding it
    if ($json -match "(?m)^'@") {
        throw "The pipeline JSON contains a line beginning with '@', which would terminate the embedded here-string. Re-save the definition with different formatting."
    }

    $corePath = Join-Path -Path (Join-Path -Path $script:ModuleRoot -ChildPath 'Core') -ChildPath 'PipelineFunctions.ps1'
    $coreSource = Get-Content -Path $corePath -Raw

    $pipelineName = if ($definition.name) { [string]$definition.name } else { (Split-Path -Path $Path -Leaf) }
    $params = @($definition.parameters | Where-Object { $_ -and $_.name })

    $lines = New-Object System.Collections.Generic.List[string]
    [void]$lines.Add('<#')
    [void]$lines.Add('    ' + $FunctionName + ' — generated by PSPipeline v0.1.0')
    [void]$lines.Add('    Pipeline : ' + $pipelineName)
    [void]$lines.Add('    Generated: ' + (Get-Date -Format 'yyyy-MM-dd HH:mm'))
    [void]$lines.Add('')
    [void]$lines.Add('    Self-contained: requires only Windows PowerShell 5.1+ (or PowerShell 7+).')
    [void]$lines.Add('    Usage:')
    [void]$lines.Add('        . .\' + $FunctionName + '.ps1')
    [void]$lines.Add('        ' + $FunctionName + ' -Verbose')
    [void]$lines.Add('#>')
    [void]$lines.Add('function ' + $FunctionName + ' {')
    [void]$lines.Add('    [CmdletBinding()]')
    [void]$lines.Add('    param(')
    [void]$lines.Add('        # Optional: directory that relative input/output paths are resolved against.')
    if ($params.Count) {
        [void]$lines.Add('        [string]$BasePath,')
        for ($pi = 0; $pi -lt $params.Count; $pi++) {
            $pDefault = ([string]$params[$pi].default).Replace("'", "''")
            $pComma = if ($pi -lt $params.Count - 1) { ',' } else { '' }
            [void]$lines.Add("        [string]`$$($params[$pi].name) = '$pDefault'$pComma")
        }
    }
    else {
        [void]$lines.Add('        [string]$BasePath')
    }
    [void]$lines.Add('    )')
    [void]$lines.Add('')
    [void]$lines.Add($coreSource.TrimEnd())
    [void]$lines.Add('')
    [void]$lines.Add("    `$pipelineJson = @'")
    [void]$lines.Add($json)
    [void]$lines.Add("'@")
    [void]$lines.Add('')
    [void]$lines.Add('    $Params = @{}')
    foreach ($p in $params) {
        [void]$lines.Add("    `$Params['$(([string]$p.name).Replace("'","''"))'] = `$$($p.name)")
    }
    [void]$lines.Add('')
    [void]$lines.Add('    if ($BasePath) { Push-Location -Path $BasePath }')
    [void]$lines.Add('    try {')
    [void]$lines.Add('        Invoke-PipelineDefinition -Definition ($pipelineJson | ConvertFrom-Json) -Parameters $Params')
    [void]$lines.Add('    }')
    [void]$lines.Add('    finally {')
    [void]$lines.Add('        if ($BasePath) { Pop-Location }')
    [void]$lines.Add('    }')
    [void]$lines.Add('}')

    $scriptText = $lines -join [Environment]::NewLine

    if ($OutputPath) {
        Set-Content -Path $OutputPath -Value $scriptText -Encoding UTF8
        Get-Item -Path $OutputPath
    }
    else {
        $scriptText
    }
}
