'use strict';
// PSPipeline PowerShell backend generator.
// Authored/tested here in Node, then mirrored into designer/index.html as the
// BACKENDS.powershell builder. Pure function of (def, engineText) -> script string.
//
// The generated .ps1 is laid out for a human to read:
//   1. comment-based help (so Get-Help works) + #Requires
//   2. a script param block (so the file can be run directly), incl. -Help
//   3. ONE small entry function, Invoke-DataPipeline -- the whole "run it" story
//   4. the embedded transform engine in a clearly fenced region
//   5. an entry-point tail: run the pipeline when executed directly, or just
//      define the function when dot-sourced.

function psStr(s) { return String(s == null ? '' : s).replace(/'/g, "''"); }

function buildPowerShellScript(def, engine) {
  const fn = 'Invoke-DataPipeline';
  const name = (def && def.name) ? String(def.name) : 'pipeline';
  const json = JSON.stringify(def, null, 2);
  if (/^'@/m.test(json)) {
    throw new Error("A value in the pipeline produces a line starting with '@, which would close the embedded here-string. Rename it and try again.");
  }
  const params = ((def && def.parameters) || []).filter(p => p && p.name);

  // .PARAMETER blocks for the script-level comment-based help
  const paramDocs = [];
  params.forEach(p => {
    const d = (p.default == null || p.default === '') ? '(empty)' : String(p.default);
    paramDocs.push('.PARAMETER ' + p.name);
    paramDocs.push('    Pipeline parameter (default: ' + d + ').');
  });

  // script-level param() -- lets the file be invoked directly; ends with -Help
  const scriptParams = ['    [string]$BasePath,']
    .concat(params.map(p => "    [string]$" + p.name + " = '" + psStr(p.default) + "',"))
    .concat(['    [switch]$Help']);

  // function-level param() -- BasePath plus the pipeline parameters (no -Help)
  const fnParams = params.length
    ? ['        [string]$BasePath,'].concat(params.map((p, i) =>
        "        [string]$" + p.name + " = '" + psStr(p.default) + "'" + (i < params.length - 1 ? ',' : '')))
    : ['        [string]$BasePath'];

  const paramAssign = ['    $Params = @{}'].concat(params.map(p =>
    "    $Params['" + psStr(p.name) + "'] = $" + p.name));

  return [
    '#Requires -Version 5.1',
    '',
    '<#',
    '.SYNOPSIS',
    '    Run the "' + name + '" data pipeline. Self-contained: no module, no install, PowerShell 5.1+.',
    '.DESCRIPTION',
    '    Generated by PSPipeline. Reads the inputs, applies the transforms, and writes the',
    '    outputs described by the pipeline embedded below. The transform engine is inlined in',
    '    the "Embedded engine" region near the foot of the file; you should not need to read',
    '    or edit it.',
    '',
    '    Run this script directly to execute the pipeline, or dot-source it to load the',
    '    ' + fn + ' function and call it yourself.',
    '.PARAMETER BasePath',
    '    Directory that relative input/output paths resolve against. Defaults to the working directory.'
  ].concat(paramDocs).concat([
    '.PARAMETER Help',
    '    Show this help and exit.',
    '.EXAMPLE',
    '    .\\' + fn + '.ps1',
    '    Run the pipeline against files in the current directory.',
    '.EXAMPLE',
    '    .\\' + fn + '.ps1 -BasePath C:\\Data -Verbose',
    '.EXAMPLE',
    '    . .\\' + fn + '.ps1; ' + fn,
    '    Dot-source to load the function, then call it.',
    '.NOTES',
    '    Pipeline : ' + name,
    '    Generated by PSPipeline.',
    '#>',
    '',
    '[CmdletBinding()]',
    'param(',
  ]).concat(scriptParams).concat([
    ')',
    '',
    'function ' + fn + ' {',
    '    <#',
    '    .SYNOPSIS',
    '        Run the embedded "' + name + '" pipeline and return its result rows.',
    '    .PARAMETER BasePath',
    '        Directory that relative input/output paths resolve against.',
    '    #>',
    '    [CmdletBinding()]',
    '    param(',
  ]).concat(fnParams).concat([
    '    )',
    '',
    "    $pipelineJson = @'",
    json,
    "'@",
    '',
  ]).concat(paramAssign).concat([
    '',
    '    if ($BasePath) { Push-Location -Path $BasePath }',
    '    try {',
    '        Invoke-PipelineDefinition -Definition ($pipelineJson | ConvertFrom-Json) -Parameters $Params',
    '    }',
    '    finally {',
    '        if ($BasePath) { Pop-Location }',
    '    }',
    '}',
    '',
    '# ===========================================================================',
    '#   Embedded transform engine',
    '#   Inlined from PSPipeline Core/PipelineFunctions.ps1 -- generated code.',
    '#   Do not edit by hand; re-export from the designer to regenerate.',
    '# ===========================================================================',
    '',
    String(engine).replace(/\s+$/, ''),
    '',
    '# ===========================================================================',
    '#   End embedded engine',
    '# ===========================================================================',
    '',
    '# Entry point: run the pipeline when this file is executed directly; when it is',
    '# dot-sourced (". .\\' + fn + '.ps1") only the function above is defined.',
    'if ($Help) { Get-Help -Name $PSCommandPath -Full; return }',
    "if ($MyInvocation.InvocationName -ne '.') {",
    "    [void]$PSBoundParameters.Remove('Help')",
    '    ' + fn + ' @PSBoundParameters',
    '}',
    ''
  ]).join('\n');
}

if (typeof module !== 'undefined' && module.exports) module.exports = { buildPowerShellScript };
